### ISSUE TITLE
Call for translators

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/website#16]
We're in the progress of moving all of our documentation to a central location #142. This place is the website, and do this we need to translate the website (coming in #14)

If you've ever wanted to contribute and help the cause of open source, now is your chance. We need you!

We're looking for translation help for the documentation in
- French
- Spanish
- Korean
- Portuguese
- Any other languages!

Our translations are managed through [crowdin](https://crowdin.com/project/all-contributors). If you want to help contribute please comment on this thread and I'll add you to the project. 

PS: This issue is a duplicate of https://github.com/all-contributors/all-contributors/issues/143

**Comment by jakebolam** [comment]
@all-contributors please add @Jongjineee for translating

**Comment by jakebolam** [comment]
Whoops didn't quite work: https://github.com/all-contributors/all-contributors-bot/pull/122/files

@all-contributors please add @Jongjineee for translations

**Comment by jakebolam** [comment]
@all-contributors please add @robertlluberes for translations

**Comment by Berkmann18** [comment]
For French (and Spanish to a little extent), I can handle that.
